name: "Code of Conduct Notifier"
description: "Hello"

inputs:
  comment-body:
    description: The comment that the bot will post about the Code of Conduct
    default: "Please refer to our current Code of Conduct: https://github.com/${context.repo.owner}/${context.repo.repo}/blob/main/CODE_OF_CONDUCT.md"

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v5
      if: contains(github.event.comment.body, 'code of conduct') 
      env:
        COMMENT: ${{ inputs.comment-body }}
      with:
        script: |
          const { COMMENT } = process.env
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Hello ${COMMENT}`
          });   
