name: "Code of Conduct Notifier"
description: "Hello"

runs:
  using: "composite"
  steps:
    - name: Install Deta CLI
      shell: bash
      run: |
        echo ${{ github.event.comment.body }}   
    - uses: actions/github-script@v5
      env:
        COMMENT: |
          Mona este
          viata mea and **markdown** support [hey](http://example.com)
      with:
        script: |
          const { COMMENT } = process.env
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Hello ${COMMENT}`
          });   
