name: "Code of Conduct Notifier"
description: "Hello"

inputs:
  coc-url:
    description: The URL to the Code of Conduct. Used to mention in the body of the comment
    default: "CODE_OF_CONDUCT.md"
  comment-body:
    description: The comment that the bot will post about the Code of Conduct
    default: "Please refer to our current Code of Conduct: <URL>"

runs:
  using: "composite"
  steps:
    - name: Build the CoC URL
      shell: bash
      run: |
        regex="https?://[^ ]+"
        if [[ "${{ inputs.coc-url }}" =~ $regex ]]
        then 
            export COCURL="${{ inputs.coc-url }}"
        else
            if [[ "${{ inputs.coc-url }}" = "/*"* ]]
            then
                export COCURL="https://github.com/${{ github.repository }}/blob/main${{ inputs.coc-url }}"
            else
                export COCURL="https://github.com/${{ github.repository }}/blob/main/${{ inputs.coc-url }}"
            fi
        fi
        
        echo $COCURL
    - uses: actions/github-script@v5
      if: contains(github.event.comment.body, 'code of conduct') 
      env:
        COMMENT: "hey"
      with:
        script: |
          const { COMMENT } = process.env
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Hello ${COMMENT}`
          });   
