name: "Code of Conduct Notifier"
description: "Hello"

runs:
  using: "composite"
  steps:
    - name: Install Deta CLI
      shell: bash
      run: |
        echo ${{ github.event.comment.body }}   
    - uses: actions/github-script@v4
        with:
          script: |
            github.reactions.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              content: "hey"
            });   
